package com.ambesoftnet.cleanvault.data.remote

import retrofit2.http.GET

/**
 * # NoteApi — Retrofit HTTP API Interface
 *
 * This interface defines the **contract** for all remote API calls related to notes.
 * Retrofit reads this interface at runtime and generates a working HTTP client implementation.
 *
 * ---
 *
 * ## What is Retrofit?
 *
 * Retrofit is a type-safe REST client library for Android and Java, made by Square.
 * Instead of manually building HTTP requests with `HttpURLConnection` or `OkHttp`,
 * you annotate an interface and Retrofit generates all the networking code.
 *
 * **Without Retrofit (verbose & error-prone):**
 * ```kotlin
 * val url = URL("https://jsonplaceholder.typicode.com/posts")
 * val conn = url.openConnection() as HttpURLConnection
 * conn.requestMethod = "GET"
 * val json = conn.inputStream.bufferedReader().readText()
 * // ...manually parse JSON with JSONObject...
 * ```
 *
 * **With Retrofit (clean & type-safe):**
 * ```kotlin
 * val notes = noteApi.getRemoteNotes()  // Returns List<NoteDto> automatically!
 * ```
 *
 * ---
 *
 * ## OOP Concept: Interface as Abstraction
 *
 * [NoteApi] is an `interface` — it defines WHAT operations exist, not HOW they work.
 * The actual HTTP implementation is generated by Retrofit at runtime through
 * **dynamic proxy** (Java reflection). This is the **Proxy Design Pattern**.
 *
 * ---
 *
 * ## `@GET("posts")` Annotation
 *
 * This annotation maps the function to an HTTP GET request:
 * ```
 * Base URL   : https://jsonplaceholder.typicode.com/
 * Endpoint   : posts
 * Full URL   : https://jsonplaceholder.typicode.com/posts
 * HTTP Method: GET
 * ```
 *
 * ---
 *
 * ## Coroutines: `suspend`
 *
 * The `suspend` keyword allows Retrofit to be called from a coroutine without
 * blocking the UI thread. Retrofit 2.6+ natively supports `suspend` functions.
 * Under the hood, it executes the HTTP call on a background thread and
 * **suspends** the calling coroutine until the response arrives.
 *
 * ---
 *
 * ## Clean Architecture: Data Layer
 *
 * [NoteApi] is part of the **Data Layer** (`data.remote`). It knows nothing about
 * the domain [com.ambesoftnet.cleanvault.domain.model.Note] or the UI.
 * The repository maps [NoteDto] → [com.ambesoftnet.cleanvault.data.local.NoteEntity].
 *
 * @see NoteDto
 * @see com.ambesoftnet.cleanvault.data.repository.NoteRepositoryImpl
 * @see com.ambesoftnet.cleanvault.di.AppModule.provideNoteApi
 */
interface NoteApi {

    /**
     * Fetches a list of notes/posts from the remote REST API.
     *
     * **Endpoint:** `GET https://jsonplaceholder.typicode.com/posts`
     *
     * The JSON response is automatically deserialized into `List<NoteDto>`
     * by the [retrofit2.converter.gson.GsonConverterFactory] configured in [com.ambesoftnet.cleanvault.di.AppModule].
     *
     * **Example JSON response:**
     * ```json
     * [
     *   {
     *     "userId": 1,
     *     "id": 1,
     *     "title": "sunt aut facere...",
     *     "body": "quia et suscipit..."
     *   },
     *   ...
     * ]
     * ```
     *
     * **Multithreading:** Being a `suspend` function, this call must be invoked
     * from within a coroutine. The actual HTTP request runs on the OkHttp thread pool
     * (not the main thread), ensuring the UI stays responsive.
     *
     * @return A [List] of [NoteDto] objects parsed from the JSON response
     * @throws retrofit2.HttpException if the server returns a non-2xx HTTP status
     * @throws java.io.IOException if there is a network connectivity problem
     */
    @GET("posts")
    suspend fun getRemoteNotes(): List<NoteDto>
}
